return kwargs from adapter.to_file funtions
Deltares/hydromt pull request #456
Opened 2023-07-25 08:28 UTC by savente93

## Issue addressed
Fixes #182

## Explanation
The description wasn't super clear about how this was supposed to be used but it was super quick to do, so I just took the liberty. For now the returned source_kwargs in the export function is unused, but hopefully, those (i.e. @DirkEilander) can use it now that it is available. This PR doesn't actually add any functionality, therefore I don't think tests or doc updates are necessary. 

## Checklist
- [x] Updated tests or added new tests
- [x] Branch is up to date with `main`
- [x] Tests & pre-commit hooks pass
- [x] Updated documentation if needed
- [x] Updated changelog.rst if needed

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

2023-07-31 14:22 UTC, DirkEilander requested changes
I added a small comment, let me know if you have questions.

2023-07-31 14:22 UTC, DirkEilander commented on hydromt/data_adapter/dataframe.py
> +        return fn_out, driver, kwargs
```suggestion
        return fn_out, driver, read_kwargs
```

2023-07-31 14:22 UTC, DirkEilander commented on hydromt/data_adapter/dataframe.py
> +            kwargs["index_col"] = obj.index.name
The kwargs in this method are used for writing a file (here csv) and not necessarily the same as for reading the same file. See different arguments in e.g. `pandas.DataFrame.to_csv` and `pandas.read_csv`. The kwargs that are returned here are later used to read back the same file and parse it into an identical python object (here pands.DataFrame). I would suggest to return a new dictionary with `read_kwargs`, which you can initialize at the start of the `to_file` method. Idem for the other DataAdapters. I agree with your approach to start with the read_kwargs that we know are required. We can easily add once we have this infrastructure.


```suggestion
       read_kwargs = dict()
        if driver is None or driver == "csv":
            # always write as CSV
            driver = "csv"
            fn_out = join(data_root, f"{data_name}.csv")
            obj.to_csv(fn_out, **kwargs)
            read_kwargs["index_col"] = obj.index.name
```

2023-07-31 14:45 UTC, savente93 commented
@DirkEilander Perhaps a tangential question, but I noticed that the `export_data` in the `test_export_global_datasets` raises the following warning: `UserWarning: using the driver setting is deprecated. Please use vector_table instead.` I'm wondering if this is something we can solve here now? We would check if the export we're doing is  a `csv` based one but that feel really inelegant. What do you think?

2023-08-01 15:50 UTC, savente93 commented
@DirkEilander implemented what we discussed. Should be good to go now.

2023-08-03 16:02 UTC, DirkEilander approved these changes
Made a small change to actually use the returned driver_kwargs.
Otherwise goot to be merged!

2023-08-03 16:24 UTC, merged