fix get_mesh after xugrid update
Deltares/hydromt pull request #848
Opened 2024-03-22 09:38 UTC by hboisgon

## Issue addressed
None defined

## Explanation
Xugrid does not support well having data variables that are not part of the grid definition and their new check grid is too restrictive on optional ugrid dims that are not part of the data variable dims.

## Checklist
- [ ] Updated tests or added new tests
- [ ] Branch is up to date with `main`
- [ ] Tests & pre-commit hooks pass
- [ ] Updated documentation if needed
- [ ] Updated changelog.rst if needed
- [ ] For predefined catalogs: update the catalog version in the file itself, the references in data/predefined_catalogs.yml, and the changelog in data/changelog.rst

2024-03-22 09:54 UTC, hboisgon commented
I added a super simple test and also tested with the more complex hydromt_delft3dfm plugin and seems it should now be solved. Can you check and review @Tjalling-dejong ?

2024-03-25 15:23 UTC, Tjalling-dejong approved these changes
LGTM 👍

2024-03-25 15:28 UTC, Tjalling-dejong requested changes
Looks good but can you remove the commented code?

2024-03-25 15:28 UTC, Tjalling-dejong commented on hydromt/models/model_mesh.py
> +                        # uds[var] = self.mesh[var]
Sorry, missed this the first time, but can you remove the commented code here

2024-03-25 15:28 UTC, Tjalling-dejong commented on hydromt/models/model_mesh.py
> +                    # uds[var] = self.mesh[var]
also here

2024-03-26 06:31 UTC, hboisgon commented
Good one! Was late Friday evening when I finished... Can you review again ?

2024-03-26 10:52 UTC, Tjalling-dejong approved these changes
LGTM 👍

2024-03-27 01:22 UTC, merged