Data catalog tests
Deltares/hydromt pull request #970
Opened 2024-05-30 09:34 UTC by savente93

## Issue addressed
Parially Fixes #937 

## Explanation
To avoid giant mega PRs I'll also submit at least a partial PR. This one at least migrates the deltares data to the new format as well. 

## General Checklist
- [ ] Updated tests or added new tests
- [ ] Branch is up to date with `main`
- [ ] Tests & pre-commit hooks pass
- [ ] Updated documentation
- [ ] Updated changelog.rst

## Data/Catalog checklist
- [ ] `data/catalogs/predefined_catalogs.yml` has not been modified.
- [ ] None of the old `data_catalog.yml` files have been chagned
- [ ] `data/chagnelog.rst` has been updated
- [ ] new file uses `LF` line endings (done automatically if you used `update_versions.py`)
- [ ] New file has been tested locally
- [ ] Tests have been added using the new file in the test suite

## Additional Notes (optional)
Add any additional notes or information that may be helpful.

2024-05-30 09:49 UTC, Jaapel requested changes
Some things are not correct. Perhaps nice to merge some of the gcsfs and aws catalog changes in test_data_adapter.py here to test those.

2024-05-30 10:10 UTC, savente93 commented
Thanks! I'll get that fixed asap

2024-05-30 10:52 UTC, savente93 commented on data/catalogs/artifact_data/registry.txt
>  v1.0.0/data_catalog.yml c8600a213e1baf397002ec0d2e2f825ae938c2a1ab266d84011356413f4d5617
by accident I think I'll revert them

2024-05-30 11:10 UTC, savente93 commented on data/catalogs/gcs_cmip6_data/v1.0.0/data_catalog.yml
> +---
should be fixed

2024-05-30 13:39 UTC, Jaapel commented on data/catalogs/deltares_data/v0.7.0/data_catalog.yml
> +        uparea: 0.000001
@DirkEilander I migrated an alias here to a new variant, or do we want these to be different entries?

2024-05-31 08:05 UTC, Jaapel approved these changes
Let's just do it. One small thing though

2024-05-31 08:05 UTC, Jaapel commented on hydromt/data_catalog.py
> +            provider = source.driver.filesystem.protocol[0]
Protocol can be
```python
pr: Union[str, Tuple[str, ...]] = _fs.protocol
```
```suggestion
            protocol = source.driver.filesystem.protocol
            if isinstance(protocol, str):
                provider: str = protocol
            else:
                provider: str = protocol[0]
```

2024-05-31 08:11 UTC, savente93 commented
I'll continue working on the skipped tests from next week on, so it should all be fixed by the next release.

2024-05-31 08:24 UTC, merged